# Generated by Django 3.0.2 on 2020-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0002_auto_20200125_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodymessage',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodymessage',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
