# Generated by Django 3.0.2 on 2020-01-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0003_auto_20200126_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodymessage',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='moodymessage',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
